# Generated by Django 2.1.7 on 2019-02-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('root_api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
